/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    food_pears_asian_01_b: THREE.Mesh
    food_pears_asian_01_c: THREE.Mesh
    food_pears_asian_01_e: THREE.Mesh
    food_pears_asian_01_d: THREE.Mesh
    food_pears_asian_01_a: THREE.Mesh
  }
  materials: {
    food_pears_asian_01: THREE.MeshStandardMaterial
  }
}

export const Pears = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/fruits/pears.gltf/food_pears_asian_01_1k.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.food_pears_asian_01_b.geometry} material={materials.food_pears_asian_01} position={[-0.01, 0.02, -0.05]} rotation={[-2.11, 0.28, 0.29]} />
      <mesh geometry={nodes.food_pears_asian_01_c.geometry} material={materials.food_pears_asian_01} position={[-0.03, 0.02, 0.03]} rotation={[-0.31, -0.53, -0.23]} />
      <mesh geometry={nodes.food_pears_asian_01_e.geometry} material={materials.food_pears_asian_01} position={[0.01, 0.02, 0.04]} rotation={[-0.11, 0.02, 0]} />
      <mesh geometry={nodes.food_pears_asian_01_d.geometry} material={materials.food_pears_asian_01} position={[0.02, 0.02, 0]} rotation={[0.49, -0.38, -1.75]} />
      <mesh geometry={nodes.food_pears_asian_01_a.geometry} material={materials.food_pears_asian_01} position={[-0.04, 0.02, -0.01]} rotation={[1.52, -0.27, 0.69]} />
    </group>
  )
}

useGLTF.preload('/models/fruits/pears.gltf/food_pears_asian_01_1k.gltf')
